# Generated by Django 4.1.3 on 2022-12-13 10:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamMateApp', '0003_alter_team_image_alter_user_image_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='fromUser',
        ),
        migrations.RemoveField(
            model_name='request',
            name='toUser',
        ),
        migrations.AddField(
            model_name='request',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
