# Generated by Django 4.1.3 on 2022-12-14 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamMateApp', '0004_remove_request_fromuser_remove_request_touser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(upload_to='D:\\Cs50_Web\\teamMate\\media'),
        ),
    ]
