# Generated by Django 4.1.3 on 2022-12-14 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamMateApp', '0005_alter_team_image_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(upload_to='user_images/'),
        ),
    ]
